### ISSUE TITLE
Melhor usar ajax pra enviar informações às views.

### ISSUE THREAD

**Issue by Mazuh** [Mazuh/Usit-Web#1]
As ferramentas estão doidas, cada uma sendo uma mistura de post e get, outras (como a dos Horários) gambiarra de get. Usar ajax seria um incremento interessantíssimo à UX, o site ficaria mais fácil de manusear e haveria um padrão mais interessante (em termos de dev) pra envio de dados ao django. Um problema pra implementar o ajax seria passar os csrf tokens por post().

**Comment by YuriStyl3** [comment]
Cara, se for botar pra frente dps, me chama pra essa parte do ajax, pq to aprendendo e tal... 
Vai continuar com django?

**Comment by Mazuh** [comment]
Provavelmente vou substituir por Asp.net, que vai ficar tudo automático. Mas ainda vai requerer ajuda em JS. Mas aí é pra depois, lá pra junho.

**Comment by YuriStyl3** [comment]
Edmilson chora de emoção
